server:
  port: 10001
  error:
    include-stacktrace: never
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://${mysql-host}/notebook_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mandatory-file-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google-client-id}
            clientSecret: ${google-client-secret}
            scope:
              - email
              - profile
